name: Market-Miner

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build the project (release mode)
        run: cargo build --release

      - name: Setup SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          if_key_exists: fail
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      
      - name: Add SSH host
        run: ssh-keyscan -H 172.234.116.162 >> ~/.ssh/known_hosts      

      - name: Deploy to VPS
        run: |
          echo "${{ secrets.ENV_FILE }}" | ssh -o StrictHostKeyChecking=no tgk@172.234.116.162 "cat > /home/tgk/code-base/Deployments/market-miner-binaries/.env"
          scp -o StrictHostKeyChecking=no -r ./target/release/market_miner tgk@172.234.116.162:/home/tgk/code-base/Deployments/market-miner-binaries/
          ssh -o StrictHostKeyChecking=no tgk@172.234.116.162 "chmod +x /home/tgk/code-base/Deployments/market-miner-binaries/market_miner"
          ssh -o StrictHostKeyChecking=no tgk@172.234.116.162 "echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S supervisorctl restart market_miner"
